create table posts
(
    id          bigint generated by default as identity,
    content     varchar(255),
    description varchar(255),
    title       varchar(255),
    primary key (id)
);
alter table posts
    add constraint UKmchce1gm7f6otpphxd6ixsdps unique (title);
create table posts (id bigint generated by default as identity, content varchar(255), description varchar(255), title varchar(255), primary key (id));
alter table posts add constraint UKmchce1gm7f6otpphxd6ixsdps unique (title);
create table posts (id bigint generated by default as identity, content varchar(255), description varchar(255), title varchar(255), primary key (id));
alter table posts add constraint UKmchce1gm7f6otpphxd6ixsdps unique (title);
