spring:
  application:
    name: ddl
  main:
    web-application-type: none
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-ource: metadata
            scripts:
              action: create
              create-target: ddl.sql